### ISSUE TITLE
Optimize meldet Verbindungsfehler in Umgebung 'processesdemo'

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1528]
**Describe the bug**
In Umgebung 'processesdemo' meldet Optimize einen Verbindungsfehler. Optimize kann sich nicht mit 'camunda-bpm' verbinden.

```
12:43:27.475 [EngineImportScheduler-1] ERROR o.c.o.s.i.e.f.d.ProcessDefinitionFetcher - Error during fetching of entities. Please check the connection with [camunda-bpm]! Make sure you have configured an authorized user
javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:942)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:794)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:687)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:686)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:432)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:323)
	at org.camunda.optimize.service.importing.engine.fetcher.definition.DefinitionFetcher.performDefinitionRequest(DefinitionFetcher.java:127)
	at org.camunda.optimize.service.importing.engine.fetcher.definition.DefinitionFetcher.lambda$fetchDefinitions$1(DefinitionFetcher.java:84)
	at org.camunda.optimize.service.importing.engine.fetcher.instance.RetryBackoffEngineEntityFetcher.fetchWithRetry(RetryBackoffEngineEntityFetcher.java:44)
	at org.camunda.optimize.service.importing.engine.fetcher.definition.DefinitionFetcher.fetchDefinitions(DefinitionFetcher.java:84)
	at org.camunda.optimize.service.importing.engine.fetcher.definition.DefinitionFetcher.fetchDefinitions(DefinitionFetcher.java:48)
	at org.camunda.optimize.service.importing.engine.mediator.ProcessDefinitionEngineImportMediator.getEntitiesNextPage(ProcessDefinitionEngineImportMediator.java:46)
	at org.camunda.optimize.service.importing.TimestampBasedImportMediator.importNextPage(TimestampBasedImportMediator.java:39)
	at org.camunda.optimize.service.importing.BackoffImportMediator.importNextPageRetryOnError(BackoffImportMediator.java:98)
	at org.camunda.optimize.service.importing.BackoffImportMediator.runImport(BackoffImportMediator.java:46)
	at org.camunda.optimize.service.importing.AbstractImportScheduler.lambda$executeImportRound$2(AbstractImportScheduler.java:99)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at org.camunda.optimize.service.importing.AbstractImportScheduler.executeImportRound(AbstractImportScheduler.java:108)
	at org.camunda.optimize.service.importing.engine.EngineImportScheduler.runImportRound(EngineImportScheduler.java:57)
	at org.camunda.optimize.service.importing.AbstractImportScheduler.runImportRound(AbstractImportScheduler.java:65)
	at org.camunda.optimize.service.importing.AbstractImportScheduler.run(AbstractImportScheduler.java:35)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**To Reproduce**
Einloggen in Optimize und Logging von Optimize überwachen.

**Expected behavior**

- [ ] Optimize kann sich mit Camunda synchronisieren.

**Screenshots**
<img width="243" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjRwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--673162a2d06be8dea3d7162400def7fbe622f944/grafik.png" alt="grafik.png" />

**Comment by markostreich** [comment]
Leider kann ich die fehlerhaften Credentials nicht ausfindig machen.

**Comment by markostreich** [comment]
Die Verbindung ist wieder hergestellt. (Ohne meine Einwirkung)
