### ISSUE TITLE
GraalVM Integration

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1703]
**Is your feature request related to a problem? Please describe.**

Als Plattformbetreiber möchte ich die Kosten der Plattform möglichst reduzieren. Dafür testen wir die Einsetzbarkeit von GraalVM an einem Integrationsservice aus.

**Describe the solution you'd like**

* verwendet wird die DMS-Integration
* Maven Buildprozess wird auf GraalVM geändert
* zunächst lokal zum Laufen bringen
* Pushen über DockerHub auf die Dev-Umgebung (manuell reicht zunächst)
* Untersuchung: Wie verändern sich CPU- und Speicherauslastung sowie die Startzeit? Tests umfassen auch Dateiup- und download

**Acceptance Criteria**

- [ ] Untersuchungsergebnis liegt vor: Ist es grundsätzlich möglich? Wie verändern sich CPU- und Speicherauslastung sowie die Startzeit?

**Time Box**

3 PT

**Addition Context**

- https://docs.spring.io/spring-boot/reference/native-image/developing-your-first-application.html#native-image.developing-your-first-application.buildpacks.maven
- https://github.com/spring-cloud/spring-cloud-stream-samples/tree/main/kafka-binder-native-app

**Comment by simonhir** [comment]
There a two ways to build a native image/executable under Spring:

## Via `spring-boot-maven-plugin`
Builds complete docker image.

By extending the [already existing build step with `spring-boot-maven-plugin`](https://github.com/it-at-m/digiwf-core/blob/dev/pom.xml#L189-L200) like following:

<details>

```
<plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                    <configuration>
                        <image>
                            <env>
                                <BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
                                <BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
                                    --initialize-at-build-time=org.slf4j.LoggerFactory
                                    --initialize-at-build-time=ch.qos.logback
                                    --initialize-at-build-time=org.bouncycastle
                                    --initialize-at-build-time=org.apache.catalina.connector
                                    --initialize-at-build-time=org.apache.catalina.util
                                    --initialize-at-build-time=org.apache.juli.logging
                                    --initialize-at-build-time=org.apache.xerces
                                    --initialize-at-build-time=org.glassfish.jaxb
                                    --initialize-at-build-time=com.ctc.wstx
                                    --initialize-at-build-time=jakarta.xml
                                    --initialize-at-build-time=com.sun.istack
                                    --initialize-at-build-time=com.sun.xml
                                </BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
                                <HTTP_PROXY>px-internetweb.muenchen.de:80</HTTP_PROXY>
                                <HTTPS_PROXY>px-internetweb.muenchen.de:80</HTTPS_PROXY>
                                <NO_PROXY>.muenchen.de</NO_PROXY>
                            </env>
                        </image>
                        <docker>
                            <builderRegistry>
                                <username>...</username>
                                <password>...</password>
                                <url>https://index.docker.io/v1/</url>
                            </builderRegistry>
                        </docker>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>repackage</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>process-aot</id>
                            <goals>
                                <goal>process-aot</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
```

</details>

## Via `native-maven-plugin`
Builds native executable.

Add additional following build step:
Requires GraalVM to be [set up](https://www.graalvm.org/latest/docs/getting-started/).

<details>

```
<plugin>
                    <groupId>org.graalvm.buildtools</groupId>
                    <artifactId>native-maven-plugin</artifactId>
                    <configuration>
                        <buildArgs>
                            <buildArg>
                                --initialize-at-build-time=org.slf4j.LoggerFactory
                                --initialize-at-build-time=ch.qos.logback
                                --initialize-at-build-time=org.bouncycastle
                                --initialize-at-build-time=org.apache.catalina.connector
                                --initialize-at-build-time=org.apache.catalina.util
                                --initialize-at-build-time=org.apache.juli.logging
                                --initialize-at-build-time=org.apache.xerces
                                --initialize-at-build-time=org.glassfish.jaxb
                                --initialize-at-build-time=com.ctc.wstx
                                --initialize-at-build-time=jakarta.xml
                                --initialize-at-build-time=com.sun.istack
                                --initialize-at-build-time=com.sun.xml
                            </buildArg>
                        </buildArgs>
                    </configuration>
                </plugin>
```

</details>

## Lessons learned

- `io.netty` requires GraalVM Reachability Metadata Repository see https://www.graalvm.org/native-image/libraries-and-frameworks/

## Tested Integrations
### digiwf-dms-integration
Can build with above config but fails at startup as `classpath:/_.wsdl` is not resolvable
```
Caused by: jakarta.xml.ws.WebServiceException: Ung³ltige WSDL-URL: classpath:/fabasoft.wsdl
```
### digiwf-emai-integration
Can build with above config but fails at startup with following error
<details>

```
2024.06.17 06:31:26.859 | ERROR | [main] | SpringApplication | [SpringApplication.java : 835] - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'digiwfEmailApi': Instantiation of supplied bean failed
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1218)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1156)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:558)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:518)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:952)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:615)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at de.muenchen.oss.digiwf.email.integration.DigiwfEmailIntegrationApplication.main(DigiwfEmailIntegrationApplication.java:10)
Caused by: java.lang.Error: java.lang.InstantiationException: org.owasp.shim.ForJava9AndLater
        at org.owasp.shim.Java8Shim.<clinit>(Java8Shim.java:27)
        at org.owasp.html.HtmlPolicyBuilder.<clinit>(HtmlPolicyBuilder.java:168)
        at org.owasp.html.Sanitizers.<clinit>(Sanitizers.java:58)
        at de.muenchen.oss.digiwf.email.impl.DigiwfEmailApiImpl.<init>(DigiwfEmailApiImpl.java:39)
        at de.muenchen.oss.digiwf.email.configuration.DigiwfEmailAutoConfiguration.digiwfEmailApi(DigiwfEmailAutoConfiguration.java:51)
        at de.muenchen.oss.digiwf.email.configuration.DigiwfEmailAutoConfiguration__BeanDefinitions.lambda$getDigiwfEmailApiInstanceSupplier$2(DigiwfEmailAutoConfiguration__BeanDefinitions.java:57)
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68)
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54)
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:202)
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:214)
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:947)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1212)
        ... 17 common frames omitted
Caused by: java.lang.InstantiationException: org.owasp.shim.ForJava9AndLater
        at java.base@17.0.11/java.lang.Class.newInstance(DynamicHub.java:639)
        at org.owasp.shim.Java8Shim.<clinit>(Java8Shim.java:21)
        ... 31 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.owasp.shim.ForJava9AndLater.<init>()
        at java.base@17.0.11/java.lang.Class.checkMethod(DynamicHub.java:1042)
        at java.base@17.0.11/java.lang.Class.getConstructor0(DynamicHub.java:1208)
        at java.base@17.0.11/java.lang.Class.newInstance(DynamicHub.java:626)
        ... 32 common frames omitted
```

</details>

### digiwf-engine-rest
```
Caused by: java.lang.NoSuchMethodException: org.camunda.bpm.engine.impl.ProcessEngineLogger.<init>()
```

## Result

When testing the native image builds one error after the other occurred and it was never really clear whether the recommended solution, such as adding the `--initialize-at-build-time` argument, was really the right way to go.
The much more practical way would be to try the whole thing with a much smaller Refarch project.

**Comment by darenegade** [comment]
Hab das intern aufgenommen:

https://git.muenchen.de/ccse/refarch-archetype/refarch-archetype-backend/-/issues/76

Für mich passt das, wenn wir wegen der Probleme hier die Komplexität erstmal reduzieren

**Comment by simonhir** [comment]
As part of the internal ticket [refarch-archetype/refarch-archetype-backend!76](https://git.muenchen.de/ccse/refarch-archetype/refarch-archetype-backend/-/issues/76), it was noticed that the custom Maven build config of DigiWF was the main cause of errors. With adjustments, the implementation should therefore be feasible, taking into account the problems documented in the issue above.
