### ISSUE TITLE
Task-Enrich bricht mit Nullpointer ab

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#473]
**Describe the bug**
Task Enrichment produces Nullpointer:

```
java.lang.NullPointerException: null
    at org.camunda.bpm.engine.impl.persistence.entity.TaskEntity.getIdentityLinks(TaskEntity.java:844)
    at org.camunda.bpm.engine.impl.persistence.entity.TaskEntity.getCandidates(TaskEntity.java:774)
    at io.muenchendigital.digiwf.task.listener.AssignmentCreateTaskListener.taskCreated(AssignmentCreateTaskListener.java:44)
    at io.muenchendigital.digiwf.task.importer.TaskImporterService.lambda$enrichExistingTasks$3(TaskImporterService.java:67) 
```

**To Reproduce**
1. Start Enrich

**Expected behavior**
All Tasks enriched

**Additional context**

Kibana Log:

https://kibana-openshift-logging.apps.capp.muenchen.de/app/kibana#/doc/8e2ca020-8141-11ed-960b-45a44d781acc/app-digiwf-p-000937/_doc?id=MjEyYTQ0OTYtN2UzNi00ZGVhLWEwNzMtYjNhYzllY2RkOWVl&_g=()

**Comment by darenegade** [comment]
@zambrovski Reicht hier ein NullPointerException-Handling? Weil dann würde ich das Thema übernehmen, damit es nicht bis morgen wartet

Ich hätte jetzt NullPointer abgefangen und Groups als Empty initialisiert

**Comment by zambrovski** [comment]
Da läuft was schief. NullPointer passiert im Camunda Code. Das deutet darauf hin, dass wir der Camunda Context nicht gesetzt ist.
