### ISSUE TITLE
Grouptasks can't be created after "Handle candidate update"

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#694]
Grouptasks can't be created after #590.
The following NullPointerException is thrown:

```
java.lang.NullPointerException: null
	at de.muenchen.oss.digiwf.task.listener.TaskUtil.getTaskCandidates(TaskUtil.java:26)
	at de.muenchen.oss.digiwf.task.listener.AssignmentAssignTaskListener.taskCandidatesChanged(AssignmentAssignTaskListener.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
```

## Reproduce
- Try to start "Example Grouptask"
-> Error is thrown

**Comment by darenegade** [comment]
Aktuell Release verhindernd, daher Prio High

**Comment by darenegade** [comment]
Aktuell Release verhindernd, daher Prio High
