### ISSUE TITLE
EzLdap Server Error

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#771]
See: https://git.muenchen.de/km23/ezLDAP/ezLDAP/-/issues/22

**Todo**

- Fix in EzLdap
- Fix in digiwf-engine legacy code

**Comment by simonhir** [comment]
As there are still some scenarios where the ou tree resolution is not working we agreed with the identity services team and @lmoesle to use the `lhmObjectReference` user attribute to get to the group.
This should be much more reliable and also faster.

**Comment by simonhir** [comment]
New problem from internal incident INC0361335 where the resolution works but one of the entries is null which causes a NullPointerException.

Log:
```
java.lang.NullPointerException: null
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at de.muenchen.oss.digiwf.legacy.user.domain.service.LdapUserServiceImpl.getGroups(LdapUserServiceImpl.java:39)
	at de.muenchen.oss.digiwf.shared.configuration.camunda.CamundaUserAuthenticationFilter.lambda$doFilter$0(CamundaUserAuthenticationFilter.java:34)
```
